-- Lot 1 : modele metier des sections 5.1 a 5.3 du cahier des charges, plus le
-- journal d'evenements (5.5). Le stock (5.4) arrive au lot 6, la planification
-- (plan, decision_plan) au lot 3.
--
-- Conventions :
--   - tous les horodatages sont en TIMESTAMPTZ, donc stockes en UTC ;
--   - les enumerations sont des VARCHAR contraints par CHECK : lisibles en SQL,
--     modifiables par migration, et pas de type ENUM PostgreSQL a faire evoluer ;
--   - aucune suppression physique des occurrences : elles passent a ANNULEE.

-- ---------------------------------------------------------------------------
-- 5.1 Utilisateurs et statuts
-- ---------------------------------------------------------------------------

CREATE TABLE utilisateur (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom                 VARCHAR(80)  NOT NULL,
    identifiant         VARCHAR(60)  NOT NULL UNIQUE,
    mot_de_passe_hash   VARCHAR(120) NOT NULL,
    role                VARCHAR(20)  NOT NULL CHECK (role IN ('ADMINISTRATEUR', 'STANDARD')),
    fuseau              VARCHAR(60)  NOT NULL DEFAULT 'Europe/Paris',
    canal_notification  VARCHAR(120),
    actif               BOOLEAN      NOT NULL DEFAULT TRUE,
    cree_le             TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE statut_utilisateur (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id  BIGINT       NOT NULL REFERENCES utilisateur (id),
    type            VARCHAR(20)  NOT NULL CHECK (type IN ('ACTIF', 'MALADE', 'ABSENT')),
    lieu            VARCHAR(120),
    debut           TIMESTAMPTZ  NOT NULL,
    fin_prevue      TIMESTAMPTZ,
    fin_reelle      TIMESTAMPTZ,
    commentaire     TEXT,
    CONSTRAINT statut_fin_coherente CHECK (fin_reelle IS NULL OR fin_reelle >= debut)
);

-- Un seul statut ouvert par utilisateur a un instant donne (cf. 5.1).
CREATE UNIQUE INDEX statut_unique_ouvert
    ON statut_utilisateur (utilisateur_id)
    WHERE fin_reelle IS NULL;

CREATE INDEX statut_par_utilisateur ON statut_utilisateur (utilisateur_id, debut DESC);

CREATE TABLE regle_statut (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_statut           VARCHAR(20) NOT NULL CHECK (type_statut IN ('ACTIF', 'MALADE', 'ABSENT')),
    categorie_tache       VARCHAR(20) NOT NULL,
    effet                 VARCHAR(20) NOT NULL CHECK (effet IN ('GELER', 'REPORTER', 'REASSIGNER', 'MAINTENIR')),
    cible_reassignation   BIGINT REFERENCES utilisateur (id),
    CONSTRAINT regle_statut_unique UNIQUE (type_statut, categorie_tache),
    CONSTRAINT regle_reassignation_coherente
        CHECK (effet <> 'REASSIGNER' OR cible_reassignation IS NOT NULL)
);

COMMENT ON TABLE regle_statut IS
    'Effets d un statut rendus configurables : ajouter un statut VACANCES ne doit pas toucher au moteur (cf. 5.1).';

-- ---------------------------------------------------------------------------
-- 5.2 Occupations, sources et deplacements
-- ---------------------------------------------------------------------------

CREATE TABLE source_contrainte (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                      VARCHAR(40) NOT NULL UNIQUE,
    libelle                   VARCHAR(120) NOT NULL,
    type_collecte             VARCHAR(20) NOT NULL CHECK (type_collecte IN ('ICS', 'SCRAPING', 'IMAP', 'MANUELLE')),
    derniere_collecte_ok      TIMESTAMPTZ,
    derniere_collecte_tentee  TIMESTAMPTZ,
    etat_sante                VARCHAR(10) NOT NULL DEFAULT 'OK' CHECK (etat_sante IN ('OK', 'DEGRADE', 'MORT')),
    ttl_fraicheur_heures      INTEGER     NOT NULL DEFAULT 24,
    configuration             TEXT,
    active                    BOOLEAN     NOT NULL DEFAULT TRUE
);

COMMENT ON COLUMN source_contrainte.ttl_fraicheur_heures IS
    'Passe ce delai sans collecte reussie, la source passe en DEGRADE puis MORT. Le moteur ne planifie jamais sur des donnees perimees sans le signaler (cf. 7.1 A.1).';

CREATE TABLE occupation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id  BIGINT       NOT NULL REFERENCES utilisateur (id),
    source_id       BIGINT       NOT NULL REFERENCES source_contrainte (id),
    type            VARCHAR(20)  NOT NULL CHECK (type IN ('COURS', 'SHIFT', 'TRAJET', 'SOMMEIL', 'PERSO')),
    debut           TIMESTAMPTZ  NOT NULL,
    fin             TIMESTAMPTZ  NOT NULL,
    lieu            VARCHAR(120),
    libelle         VARCHAR(200) NOT NULL,
    cle_externe     VARCHAR(200),
    annulee         BOOLEAN      NOT NULL DEFAULT FALSE,
    collectee_le    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT occupation_intervalle_valide CHECK (fin > debut)
);

-- La cle externe permet la reconciliation entre deux collectes : on met a jour
-- au lieu de dupliquer (cf. 5.2).
CREATE UNIQUE INDEX occupation_cle_externe_unique
    ON occupation (source_id, cle_externe)
    WHERE cle_externe IS NOT NULL;

CREATE INDEX occupation_par_periode ON occupation (utilisateur_id, debut, fin) WHERE annulee = FALSE;

CREATE TABLE trajet (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id        BIGINT       NOT NULL REFERENCES utilisateur (id),
    sens                  VARCHAR(10)  NOT NULL CHECK (sens IN ('ALLER', 'RETOUR')),
    depart                TIMESTAMPTZ  NOT NULL,
    arrivee               TIMESTAMPTZ  NOT NULL,
    gare_depart           VARCHAR(120) NOT NULL,
    gare_arrivee          VARCHAR(120) NOT NULL,
    etat                  VARCHAR(10)  NOT NULL DEFAULT 'SUGGERE' CHECK (etat IN ('SUGGERE', 'CONFIRME', 'ANNULE')),
    source_confirmation   VARCHAR(10)  CHECK (source_confirmation IN ('MAIL', 'MANUEL')),
    reference_billet      VARCHAR(80),
    CONSTRAINT trajet_intervalle_valide CHECK (arrivee > depart)
);

CREATE INDEX trajet_par_periode ON trajet (utilisateur_id, depart);

-- ---------------------------------------------------------------------------
-- 5.3 Taches
-- ---------------------------------------------------------------------------

CREATE TABLE definition_tache (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    VARCHAR(40)  NOT NULL UNIQUE,
    libelle                 VARCHAR(120) NOT NULL,
    categorie               VARCHAR(20)  NOT NULL
                            CHECK (categorie IN ('MENAGE', 'LINGE', 'VAISSELLE', 'ANIMAL', 'SPORT', 'ADMIN')),
    priorite                SMALLINT     NOT NULL CHECK (priorite BETWEEN 0 AND 5),
    duree_minutes           INTEGER      NOT NULL CHECK (duree_minutes > 0),
    intervalle_min_jours    INTEGER      NOT NULL CHECK (intervalle_min_jours > 0),
    intervalle_max_jours    INTEGER      NOT NULL CHECK (intervalle_max_jours > 0),
    assignation_par_defaut  BIGINT REFERENCES utilisateur (id),
    gelable                 BOOLEAN      NOT NULL DEFAULT TRUE,
    fenetre_horaire_debut   TIME,
    fenetre_horaire_fin     TIME,
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT definition_intervalle_coherent CHECK (intervalle_max_jours >= intervalle_min_jours)
);

COMMENT ON COLUMN definition_tache.gelable IS
    'FALSE pour la litiere : seule categorie qui reste due meme en statut MALADE (cf. 7.4 D.4).';

CREATE TABLE dependance_tache (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_source_id  BIGINT      NOT NULL REFERENCES definition_tache (id),
    definition_cible_id   BIGINT      NOT NULL REFERENCES definition_tache (id),
    type                  VARCHAR(20) NOT NULL DEFAULT 'DECLENCHE_APRES' CHECK (type IN ('DECLENCHE_APRES')),
    delai_max_heures      INTEGER     NOT NULL CHECK (delai_max_heures > 0),
    CONSTRAINT dependance_unique UNIQUE (definition_source_id, definition_cible_id),
    CONSTRAINT dependance_non_reflexive CHECK (definition_source_id <> definition_cible_id)
);

CREATE TABLE occurrence_tache (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_id           BIGINT       NOT NULL REFERENCES definition_tache (id),
    assigne_a               BIGINT REFERENCES utilisateur (id),
    echeance_min            TIMESTAMPTZ  NOT NULL,
    echeance_max            TIMESTAMPTZ  NOT NULL,
    creneau_debut           TIMESTAMPTZ,
    creneau_fin             TIMESTAMPTZ,
    epinglee                BOOLEAN      NOT NULL DEFAULT FALSE,
    etat                    VARCHAR(20)  NOT NULL DEFAULT 'PLANIFIEE'
                            CHECK (etat IN ('PLANIFIEE', 'NOTIFIEE', 'VALIDEE', 'REPORTEE',
                                            'REFUSEE', 'GELEE', 'ANNULEE', 'NON_PLANIFIABLE')),
    origine                 VARCHAR(20)  NOT NULL DEFAULT 'AUTOMATIQUE'
                            CHECK (origine IN ('AUTOMATIQUE', 'MANUELLE', 'DEPENDANCE', 'RATTRAPAGE')),
    motif                   TEXT,
    validee_le              TIMESTAMPTZ,
    validee_par             BIGINT REFERENCES utilisateur (id),
    occurrence_parente_id   BIGINT REFERENCES occurrence_tache (id),
    creee_le                TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT occurrence_fenetre_coherente CHECK (echeance_max >= echeance_min),
    CONSTRAINT occurrence_creneau_coherent
        CHECK (creneau_fin IS NULL OR creneau_debut IS NULL OR creneau_fin > creneau_debut),
    CONSTRAINT occurrence_validation_coherente
        CHECK (etat <> 'VALIDEE' OR validee_le IS NOT NULL)
);

CREATE INDEX occurrence_ouvertes
    ON occurrence_tache (definition_id, etat)
    WHERE etat IN ('PLANIFIEE', 'NOTIFIEE', 'GELEE', 'NON_PLANIFIABLE');

CREATE INDEX occurrence_par_echeance ON occurrence_tache (echeance_max);
CREATE INDEX occurrence_par_assigne  ON occurrence_tache (assigne_a, etat);

-- ---------------------------------------------------------------------------
-- 5.5 Journal d'evenements
-- ---------------------------------------------------------------------------

CREATE TABLE journal_evenement (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    acteur        VARCHAR(60)  NOT NULL,
    type          VARCHAR(60)  NOT NULL,
    entite        VARCHAR(60)  NOT NULL,
    entite_id     BIGINT,
    valeur_avant  TEXT,
    valeur_apres  TEXT,
    correlation   VARCHAR(60)
);

COMMENT ON TABLE journal_evenement IS
    'Toute action manuelle est journalisee avec auteur, horodatage et valeur precedente (cf. 3.3).';

CREATE INDEX journal_par_entite ON journal_evenement (entite, entite_id, date DESC);
CREATE INDEX journal_par_date   ON journal_evenement (date DESC);
