-- rejouable : ce fichier ne contient que des CREATE OR REPLACE ou des IF NOT
--             EXISTS. Le rejouer après modification est sans effet de bord.
-- =============================================================================
-- 009 — Courriels de confirmation SNCF                               (R72–R76)
-- =============================================================================
-- Acheter un billet est déjà une déclaration d'absence : la refaire à la main
-- dans le bot est du travail en double, et du travail en double finit par ne
-- plus être fait. On lit donc la confirmation.
--
-- Cette table ne stocke pas les courriels. Elle garde de quoi savoir lequel a
-- déjà été vu, et ce qu'on en a fait — y compris quand on n'a rien su en
-- faire, car c'est précisément ce cas-là qui permet de corriger l'analyse.
-- =============================================================================

CREATE TABLE IF NOT EXISTS courriel (
    id_courriel    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- R72 : l'en-tête Message-ID est l'identité d'un courriel. S'y fier évite
    -- de redéclarer la même absence à chaque relève.
    identifiant    VARCHAR(255) NOT NULL UNIQUE,
    expediteur     VARCHAR(255) NOT NULL,
    sujet          VARCHAR(500),
    recu_le        TIMESTAMPTZ,

    statut         VARCHAR(20)  NOT NULL
                                CHECK (statut IN ('traite', 'ignore',
                                                  'illisible', 'refuse')),
    motif          TEXT,
    reference      VARCHAR(20),

    id_utilisateur INTEGER      REFERENCES utilisateur (id_utilisateur)
                                ON DELETE SET NULL,
    id_absence     INTEGER      REFERENCES absence (id_absence) ON DELETE SET NULL,
    traite_le      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS courriel_par_statut ON courriel (statut, traite_le DESC);

COMMENT ON TABLE courriel IS
    'Trace de ce qui a été lu dans la boîte, et de ce qu''on en a fait (R72).';

COMMENT ON COLUMN courriel.statut IS
    'traite : une absence en est née. ignore : expéditeur non reconnu ou '
    'courriel sans billet. illisible : expéditeur légitime mais analyse '
    'échouée — à corriger (R75). refuse : billet lu, mais la base a refusé '
    'l''absence, par exemple parce qu''elle en chevauche une autre.';


-- -----------------------------------------------------------------------------
-- Vue : ce qui demande une correction                                     (R75)
--
-- Un courriel qu'on n'a pas su lire n'est pas une erreur à effacer, c'est la
-- seule information disponible sur un format qui a changé. On le remonte.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_courriel_a_revoir AS
SELECT c.id_courriel,
       c.identifiant,
       c.expediteur,
       c.sujet,
       c.recu_le,
       c.statut,
       c.motif
  FROM courriel c
 WHERE c.statut IN ('illisible', 'refuse')
 ORDER BY c.traite_le DESC;
