-- rejouable : ce fichier ne contient que des CREATE OR REPLACE ou des IF NOT
--             EXISTS. Le rejouer après modification est sans effet de bord.
-- =============================================================================
-- 009 : courriels de confirmation SNCF                        (BIL-1 à BIL-9)
--
-- Acheter un billet est déjà une déclaration d'absence : la ressaisir dans le
-- bot est du travail en double. On lit donc la confirmation.
--
-- Cette table ne stocke pas les courriels, seulement lesquels ont été vus et
-- ce qu'on en a fait — y compris quand on n'a rien su en faire (BIL-8).
-- =============================================================================

CREATE TABLE IF NOT EXISTS courriel (
    id_courriel    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- BIL-1 : l'en-tête Message-ID est l'identité d'un courriel. S'y fier évite
    -- de redéclarer la même absence à chaque relève.
    identifiant    VARCHAR(255) NOT NULL UNIQUE,
    expediteur     VARCHAR(255) NOT NULL,
    sujet          VARCHAR(500),
    recu_le        TIMESTAMPTZ,

    statut         VARCHAR(20)  NOT NULL
                                CHECK (statut IN ('traite', 'ignore',
                                                  'illisible', 'refuse')),
    motif          TEXT,
    reference      VARCHAR(20),

    id_utilisateur INTEGER      REFERENCES utilisateur (id_utilisateur)
                                ON DELETE SET NULL,
    id_absence     INTEGER      REFERENCES absence (id_absence) ON DELETE SET NULL,
    traite_le      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS courriel_par_statut ON courriel (statut, traite_le DESC);

COMMENT ON TABLE courriel IS
    'Trace de ce qui a été lu dans la boîte, et de ce qu''on en a fait (BIL-1).';

COMMENT ON COLUMN courriel.statut IS
    'traite : une absence en est née. ignore : expéditeur non reconnu ou '
    'courriel sans billet. illisible : expéditeur légitime mais analyse '
    'échouée — à corriger (BIL-8). refuse : billet lu, mais la base a refusé '
    'l''absence, par exemple parce qu''elle en chevauche une autre.';


-- -----------------------------------------------------------------------------
-- Vue : ce qui demande une correction                                     (BIL-8)
--
-- Un courriel qu'on n'a pas su lire n'est pas une erreur à effacer, c'est la
-- seule information disponible sur un format qui a changé. On le remonte.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_courriel_a_revoir AS
SELECT c.id_courriel,
       c.identifiant,
       c.expediteur,
       c.sujet,
       c.recu_le,
       c.statut,
       c.motif
  FROM courriel c
 WHERE c.statut IN ('illisible', 'refuse')
 ORDER BY c.traite_le DESC;
