-- rejouable : ce fichier ne contient que des CREATE OR REPLACE et des IF NOT
--             EXISTS.
-- =============================================================================
-- 012 : propositions de week-end                              (WKD-1 à WKD-5)
--
-- Le système savait repérer un creux de deux jours, mais ne le disait que sur
-- demande. Il l'annonce désormais quinze jours avant, et relance une fois
-- trois jours avant.
--
-- Une proposition n'est pas une absence : elle s'affiche au calendrier et
-- n'a aucun effet sur le placement (WKD-1).
-- =============================================================================

CREATE TABLE IF NOT EXISTS proposition (
    id_proposition BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur INTEGER      NOT NULL REFERENCES utilisateur (id_utilisateur)
                                ON DELETE CASCADE,
    periode        TSTZRANGE    NOT NULL CHECK (NOT isempty(periode)
                                                AND lower(periode) IS NOT NULL
                                                AND upper(periode) IS NOT NULL),
    lieu           VARCHAR(100),
    statut         VARCHAR(20)  NOT NULL DEFAULT 'proposee'
                                CHECK (statut IN ('proposee', 'ecartee',
                                                  'realisee', 'perimee')),
    annoncee_le    TIMESTAMPTZ,
    relancee_le    TIMESTAMPTZ,
    date_creation  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- WKD-2 : deux propositions en cours ne peuvent pas se chevaucher. Évite
    -- de reproposer le même week-end à chaque collecte, les bornes de la
    -- fenêtre bougeant de quelques heures d'une fois sur l'autre.
    CONSTRAINT proposition_sans_doublon
        EXCLUDE USING gist (id_utilisateur WITH =, periode WITH &&)
        WHERE (statut = 'proposee')
);

CREATE INDEX IF NOT EXISTS proposition_a_traiter
    ON proposition (statut, lower(periode));

COMMENT ON TABLE proposition IS
    'Suggestion de week-end, sans effet sur le planning. Devient une absence
     seulement si on retient un trajet (WKD-1).';


-- La notification doit pouvoir renvoyer à ce qu'elle annonce, sinon le bot ne
-- sait pas à quoi accrocher ses boutons.
ALTER TABLE notification
    ADD COLUMN IF NOT EXISTS id_proposition BIGINT
        REFERENCES proposition (id_proposition) ON DELETE CASCADE;


-- -----------------------------------------------------------------------------
-- v_planning est définie dans `013_sport.sql`, et non ici.
--
-- Elle réunit occupations, tâches placées et propositions, et nomme désormais
-- le lieu d'une séance de sport — table qui n'existe qu'à partir de 013. Une
-- vue ne peut pas précéder ce qu'elle interroge : elle suit donc la dernière
-- migration qui l'élargit, et reste définie une seule fois.
-- -----------------------------------------------------------------------------


-- -----------------------------------------------------------------------------
-- Entretien : ce que le temps a tranché                                   (WKD-3)
--
-- Une proposition dont le week-end est passé n'attend plus de réponse, et une
-- proposition couverte par une absence a obtenu la sienne — qu'elle soit
-- venue d'un billet, du bot ou d'un départ déclaré à la main.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION entretenir_propositions() RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE
    v_touchees INTEGER := 0;
    v_lot      INTEGER;
BEGIN
    UPDATE proposition
       SET statut = 'realisee'
     WHERE statut = 'proposee'
       AND EXISTS (SELECT 1 FROM absence a
                    WHERE a.id_utilisateur = proposition.id_utilisateur
                      AND a.periode && proposition.periode);
    GET DIAGNOSTICS v_lot = ROW_COUNT;
    v_touchees := v_lot;

    UPDATE proposition
       SET statut = 'perimee'
     WHERE statut IN ('proposee', 'ecartee')
       AND upper(periode) < now();
    GET DIAGNOSTICS v_lot = ROW_COUNT;

    RETURN v_touchees + v_lot;
END $$;


-- -----------------------------------------------------------------------------
-- Repérer les week-ends libres                                       (WKD-1, WKD-4)
--
-- On cherche les fenêtres au-delà du délai demandé, puis on filtre. Sinon une
-- fenêtre à cheval sur l'horizon est tronquée et perd sa durée minimale.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION proposer_weekends(
    p_utilisateur  INTEGER,
    p_lieu         VARCHAR DEFAULT NULL,
    p_delai_jours  INTEGER DEFAULT 14,
    p_duree_heures INTEGER DEFAULT 48
) RETURNS SETOF proposition LANGUAGE plpgsql AS $$
BEGIN
    PERFORM entretenir_propositions();

    RETURN QUERY
    INSERT INTO proposition (id_utilisateur, periode, lieu)
    SELECT p_utilisateur, tstzrange(f.debut, f.fin, '[)'), p_lieu
      FROM fenetres_de_depart(p_utilisateur, now(),
                              now() + make_interval(days => p_delai_jours + 10),
                              p_duree_heures) f
     WHERE f.debut <= now() + make_interval(days => p_delai_jours)
       -- Ni déjà proposé, ni déjà refusé : revenir à la charge sur un week-end
       -- qu'on a décliné est le meilleur moyen de faire couper les alertes.
       AND NOT EXISTS (
           SELECT 1 FROM proposition p
            WHERE p.id_utilisateur = p_utilisateur
              AND p.periode && tstzrange(f.debut, f.fin, '[)')
              AND p.statut <> 'perimee')
       -- Ni déjà parti : une absence déclarée vaut réponse.
       AND NOT EXISTS (
           SELECT 1 FROM absence a
            WHERE a.id_utilisateur = p_utilisateur
              AND a.periode && tstzrange(f.debut, f.fin, '[)'))
    RETURNING *;
END $$;

COMMENT ON FUNCTION proposer_weekends IS
    'Crée une proposition par creux assez long commençant dans le délai donné.
     Idempotente : rejouée le lendemain, elle ne crée rien de nouveau (WKD-2).';


-- -----------------------------------------------------------------------------
-- Relancer, une fois                                                      (WKD-5)
--
-- Une seule relance, et seulement si la première annonce est restée sans
-- réponse. Pas de troisième.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION propositions_a_relancer(
    p_jours INTEGER DEFAULT 3
) RETURNS SETOF proposition LANGUAGE sql STABLE AS $$
    SELECT *
      FROM proposition
     WHERE statut = 'proposee'
       AND annoncee_le IS NOT NULL
       AND relancee_le IS NULL
       -- Jamais le jour de l'annonce : un week-end repéré trois jours avant
       -- serait annoncé et relancé dans la foulée.
       AND jour_de(annoncee_le) < jour_de(now())
       AND lower(periode) <= now() + make_interval(days => p_jours)
       AND lower(periode) > now()
     ORDER BY lower(periode);
$$;
