-- rejouable : ce fichier ne contient que des CREATE OR REPLACE et des IF NOT
--             EXISTS.
-- =============================================================================
-- 012 — Propositions de week-end                                     (R86–R90)
-- =============================================================================
-- Le système sait depuis longtemps repérer un creux de deux jours. Il ne le
-- disait que si on le lui demandait, ce qui suppose d'y penser — et si l'on y
-- pensait, on n'aurait pas besoin du système.
--
-- Deux échéances, et deux seulement. Quinze jours avant, parce qu'un billet
-- pris tôt coûte moins cher et qu'on peut encore s'organiser. Trois jours
-- avant, parce qu'entre les deux on a oublié.
--
-- Une proposition n'est pas une absence. Elle n'a aucun effet sur le ménage :
-- elle s'affiche au calendrier et attend une réponse. Confondre les deux
-- gèlerait des journées sur une simple suggestion.
-- =============================================================================

CREATE TABLE IF NOT EXISTS proposition (
    id_proposition BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilisateur INTEGER      NOT NULL REFERENCES utilisateur (id_utilisateur)
                                ON DELETE CASCADE,
    periode        TSTZRANGE    NOT NULL CHECK (NOT isempty(periode)
                                                AND lower(periode) IS NOT NULL
                                                AND upper(periode) IS NOT NULL),
    lieu           VARCHAR(100),
    statut         VARCHAR(20)  NOT NULL DEFAULT 'proposee'
                                CHECK (statut IN ('proposee', 'ecartee',
                                                  'realisee', 'perimee')),
    annoncee_le    TIMESTAMPTZ,
    relancee_le    TIMESTAMPTZ,
    date_creation  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- R87 : deux propositions vivantes ne se chevauchent pas. Un cours ajouté
    -- déplace les bornes d'une fenêtre de quelques heures ; sans cette
    -- contrainte, le même week-end serait proposé une fois par collecte.
    CONSTRAINT proposition_sans_doublon
        EXCLUDE USING gist (id_utilisateur WITH =, periode WITH &&)
        WHERE (statut = 'proposee')
);

CREATE INDEX IF NOT EXISTS proposition_a_traiter
    ON proposition (statut, lower(periode));

COMMENT ON TABLE proposition IS
    'Suggestion de week-end, sans effet sur le planning. Devient une absence
     seulement si on retient un trajet (R86).';


-- La notification doit pouvoir renvoyer à ce qu'elle annonce, sinon le bot ne
-- sait pas à quoi accrocher ses boutons.
ALTER TABLE notification
    ADD COLUMN IF NOT EXISTS id_proposition BIGINT
        REFERENCES proposition (id_proposition) ON DELETE CASCADE;


-- -----------------------------------------------------------------------------
-- Planning consolidé                                                (R29, R86)
--
-- Définie ici et non dans `002_vues.sql` : elle interroge `proposition`, qui
-- n'existe qu'à partir de ce fichier, et une vue ne peut pas précéder ce
-- qu'elle lit. Une seule définition, quitte à ce qu'elle ne soit pas rangée
-- avec ses semblables — une vue en double finit toujours par diverger.
--
-- DROP puis CREATE, et non CREATE OR REPLACE : la colonne `id` passe d'INTEGER
-- à BIGINT du fait des propositions, et PostgreSQL refuse de changer le type
-- d'une colonne de vue en place. Sans CASCADE, volontairement : si une autre
-- vue venait un jour à en dépendre, mieux vaut que la migration échoue bruyamment
-- que de la voir disparaître en silence.
-- -----------------------------------------------------------------------------
DROP VIEW IF EXISTS v_planning;

CREATE VIEW v_planning AS
SELECT
    'occupation'                       AS nature,
    o.id_occupation::BIGINT            AS id,
    o.id_utilisateur,
    o.type                             AS categorie,
    o.libelle,
    o.periode,
    lower(o.periode)                   AS debut,
    upper(o.periode)                   AS fin,
    FALSE                              AS journee_entiere,
    NULL::VARCHAR                      AS statut,
    o.lieu,
    o.details                          AS motif,
    0                                  AS nb_relances
FROM occupation o

UNION ALL

SELECT
    'tache'                            AS nature,
    o.id_occurrence::BIGINT            AS id,
    o.id_utilisateur,
    t.categorie,
    t.libelle,
    o.creneau                          AS periode,
    lower(o.creneau)                   AS debut,
    upper(o.creneau)                   AS fin,
    o.rappel_journee                   AS journee_entiere,
    o.statut,
    NULL::VARCHAR                      AS lieu,
    o.motif,
    o.nb_relances
FROM occurrence o
JOIN tache t ON t.id_tache = o.id_tache
WHERE o.creneau IS NOT NULL
  AND o.statut IN ('planifiee', 'notifiee')

UNION ALL

-- R86 : une proposition n'occupe rien et ne gèle rien. Elle s'affiche pour
-- qu'on y pense, et quitte le calendrier dès qu'on a répondu.
SELECT
    'proposition'                      AS nature,
    p.id_proposition                   AS id,
    p.id_utilisateur,
    'trajet'                           AS categorie,
    'Week-end libre'
        || COALESCE(' à ' || p.lieu, '') || ' ?'  AS libelle,
    p.periode,
    lower(p.periode)                   AS debut,
    upper(p.periode)                   AS fin,
    TRUE                               AS journee_entiere,
    p.statut,
    p.lieu,
    'Repéré par le système : aucune obligation sur cette période' AS motif,
    0                                  AS nb_relances
FROM proposition p
WHERE p.statut = 'proposee';

COMMENT ON VIEW v_planning IS
    'Occupations, tâches placées et propositions dans une seule vue. Le drapeau
     journee_entiere décide si l''export produit un VEVENT horaire ou un
     VEVENT journée entière (R29).';


-- -----------------------------------------------------------------------------
-- Entretien : ce que le temps a tranché                                   (R88)
--
-- Une proposition dont le week-end est passé n'attend plus de réponse, et une
-- proposition couverte par une absence a obtenu la sienne — qu'elle soit
-- venue d'un billet, du bot ou d'un départ déclaré à la main.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION entretenir_propositions() RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE
    v_touchees INTEGER := 0;
    v_lot      INTEGER;
BEGIN
    UPDATE proposition
       SET statut = 'realisee'
     WHERE statut = 'proposee'
       AND EXISTS (SELECT 1 FROM absence a
                    WHERE a.id_utilisateur = proposition.id_utilisateur
                      AND a.periode && proposition.periode);
    GET DIAGNOSTICS v_lot = ROW_COUNT;
    v_touchees := v_lot;

    UPDATE proposition
       SET statut = 'perimee'
     WHERE statut IN ('proposee', 'ecartee')
       AND upper(periode) < now();
    GET DIAGNOSTICS v_lot = ROW_COUNT;

    RETURN v_touchees + v_lot;
END $$;


-- -----------------------------------------------------------------------------
-- Repérer les week-ends libres                                       (R86, R89)
--
-- On regarde plus loin que le délai voulu avant de filtrer : une fenêtre qui
-- commence dans treize jours et finit dans seize serait tronquée par
-- l'horizon, et passerait sous les quarante-huit heures pour une raison qui
-- n'a rien à voir avec l'emploi du temps.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION proposer_weekends(
    p_utilisateur  INTEGER,
    p_lieu         VARCHAR DEFAULT NULL,
    p_delai_jours  INTEGER DEFAULT 14,
    p_duree_heures INTEGER DEFAULT 48
) RETURNS SETOF proposition LANGUAGE plpgsql AS $$
BEGIN
    PERFORM entretenir_propositions();

    RETURN QUERY
    INSERT INTO proposition (id_utilisateur, periode, lieu)
    SELECT p_utilisateur, tstzrange(f.debut, f.fin, '[)'), p_lieu
      FROM fenetres_de_depart(p_utilisateur, now(),
                              now() + make_interval(days => p_delai_jours + 10),
                              p_duree_heures) f
     WHERE f.debut <= now() + make_interval(days => p_delai_jours)
       -- Ni déjà proposé, ni déjà refusé : revenir à la charge sur un week-end
       -- qu'on a décliné est le meilleur moyen de faire couper les alertes.
       AND NOT EXISTS (
           SELECT 1 FROM proposition p
            WHERE p.id_utilisateur = p_utilisateur
              AND p.periode && tstzrange(f.debut, f.fin, '[)')
              AND p.statut <> 'perimee')
       -- Ni déjà parti : une absence déclarée vaut réponse.
       AND NOT EXISTS (
           SELECT 1 FROM absence a
            WHERE a.id_utilisateur = p_utilisateur
              AND a.periode && tstzrange(f.debut, f.fin, '[)'))
    RETURNING *;
END $$;

COMMENT ON FUNCTION proposer_weekends IS
    'Crée une proposition par creux assez long commençant dans le délai donné.
     Idempotente : rejouée le lendemain, elle ne crée rien de nouveau (R87).';


-- -----------------------------------------------------------------------------
-- Relancer, une fois                                                      (R90)
--
-- Une seule relance, et seulement si la première est restée sans réponse.
-- Répéter tous les jours transformerait un service en harcèlement, et la
-- réponse serait de couper les notifications.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION propositions_a_relancer(
    p_jours INTEGER DEFAULT 3
) RETURNS SETOF proposition LANGUAGE sql STABLE AS $$
    SELECT *
      FROM proposition
     WHERE statut = 'proposee'
       AND annoncee_le IS NOT NULL
       AND relancee_le IS NULL
       -- Jamais le jour de l'annonce. Un week-end repéré trois jours avant
       -- serait sinon annoncé puis relancé dans la même minute, ce qui n'est
       -- pas un rappel mais un bégaiement.
       AND jour_de(annoncee_le) < jour_de(now())
       AND lower(periode) <= now() + make_interval(days => p_jours)
       AND lower(periode) > now()
     ORDER BY lower(periode);
$$;
