-- Rejouable.
-- Le catalogue d'exercices de départ                                    (EXO-4)
--
-- Rempli d'après les chapitres 4.4, 4.5 et 6.3 du dossier du coach, pour le
-- matériel d'une salle complète. Ce fichier est produit à partir de
-- coach/catalogue/exercices.json, qui se lit plus facilement. Un exercice déjà
-- présent n'est pas touché : le catalogue se corrige ensuite par une migration
-- nouvelle, et un exercice ne se supprime pas, il se désactive (EXO-3).

INSERT INTO exercice (code, libelle, discipline, groupe_principal, groupes_secondaires,
                      materiel, unilateral, mesure) VALUES
    ('developpe_couche_barre', 'Développé couché barre', 'musculation', 'pectoraux', '{triceps,epaules}', 'barre', FALSE, 'charge_reps'),
    ('developpe_couche_smith', 'Développé couché au cadre guidé', 'musculation', 'pectoraux', '{triceps,epaules}', 'machine', FALSE, 'charge_reps'),
    ('developpe_couche_halteres', 'Développé couché haltères', 'musculation', 'pectoraux', '{triceps,epaules}', 'halteres', FALSE, 'charge_reps'),
    ('developpe_incline_barre', 'Développé incliné barre', 'musculation', 'pectoraux', '{epaules,triceps}', 'barre', FALSE, 'charge_reps'),
    ('developpe_incline_halteres', 'Développé incliné haltères', 'musculation', 'pectoraux', '{epaules,triceps}', 'halteres', FALSE, 'charge_reps'),
    ('presse_pectoraux', 'Presse à pectoraux', 'musculation', 'pectoraux', '{triceps,epaules}', 'machine', FALSE, 'charge_reps'),
    ('presse_inclinee', 'Presse inclinée', 'musculation', 'pectoraux', '{epaules,triceps}', 'machine', FALSE, 'charge_reps'),
    ('pec_deck', 'Pec deck', 'musculation', 'pectoraux', '{}', 'machine', FALSE, 'charge_reps'),
    ('ecartes_halteres', 'Écartés haltères', 'musculation', 'pectoraux', '{}', 'halteres', FALSE, 'charge_reps'),
    ('ecartes_poulies', 'Écartés aux poulies', 'musculation', 'pectoraux', '{}', 'poulie', FALSE, 'charge_reps'),
    ('pompes', 'Pompes', 'musculation', 'pectoraux', '{triceps,epaules}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('tractions_pronation', 'Tractions prise pronation', 'musculation', 'dos', '{biceps,avant_bras}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('tractions_supination', 'Tractions prise supination', 'musculation', 'dos', '{biceps}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('tractions_neutre', 'Tractions prise neutre', 'musculation', 'dos', '{biceps,avant_bras}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('tractions_assistees', 'Tractions assistées', 'musculation', 'dos', '{biceps}', 'machine', FALSE, 'charge_reps'),
    ('tirage_vertical_large', 'Tirage vertical prise large', 'musculation', 'dos', '{biceps}', 'machine', FALSE, 'charge_reps'),
    ('tirage_vertical_neutre', 'Tirage vertical prise neutre', 'musculation', 'dos', '{biceps,avant_bras}', 'machine', FALSE, 'charge_reps'),
    ('tirage_vertical_supination', 'Tirage vertical prise supination', 'musculation', 'dos', '{biceps}', 'machine', FALSE, 'charge_reps'),
    ('tirage_bras_tendus', 'Tirage bras tendus à la poulie', 'musculation', 'dos', '{}', 'poulie', FALSE, 'charge_reps'),
    ('tirage_unilateral_poulie', 'Tirage unilatéral à la poulie haute', 'musculation', 'dos', '{biceps}', 'poulie', TRUE, 'charge_reps'),
    ('rowing_barre', 'Rowing barre buste penché, prise pronation', 'musculation', 'dos', '{biceps,lombaires}', 'barre', FALSE, 'charge_reps'),
    ('rowing_barre_supination', 'Rowing barre prise supination', 'musculation', 'dos', '{biceps,lombaires}', 'barre', FALSE, 'charge_reps'),
    ('rowing_haltere_un_bras', 'Rowing haltère un bras, prise neutre', 'musculation', 'dos', '{biceps,avant_bras}', 'halteres', TRUE, 'charge_reps'),
    ('rowing_haltere_rotation', 'Rowing haltère avec rotation', 'musculation', 'dos', '{biceps}', 'halteres', TRUE, 'charge_reps'),
    ('rowing_assis_machine', 'Rowing assis machine', 'musculation', 'dos', '{biceps}', 'machine', FALSE, 'charge_reps'),
    ('rowing_poulie_basse', 'Rowing à la poulie basse, poignée neutre', 'musculation', 'dos', '{biceps}', 'poulie', FALSE, 'charge_reps'),
    ('rowing_t_appui', 'Rowing barre en T avec appui poitrine', 'musculation', 'dos', '{biceps}', 'machine', FALSE, 'charge_reps'),
    ('rowing_inverse', 'Rowing inversé à la barre ou aux sangles', 'musculation', 'dos', '{biceps}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('haussements_halteres', 'Haussements d''épaules haltères', 'musculation', 'dos', '{avant_bras}', 'halteres', FALSE, 'charge_reps'),
    ('developpe_militaire_barre', 'Développé militaire barre', 'musculation', 'epaules', '{triceps}', 'barre', FALSE, 'charge_reps'),
    ('developpe_epaules_halteres', 'Développé épaules haltères assis', 'musculation', 'epaules', '{triceps}', 'halteres', FALSE, 'charge_reps'),
    ('developpe_arnold', 'Développé Arnold', 'musculation', 'epaules', '{triceps}', 'halteres', FALSE, 'charge_reps'),
    ('presse_epaules', 'Presse à épaules', 'musculation', 'epaules', '{triceps}', 'machine', FALSE, 'charge_reps'),
    ('elevations_laterales_halteres', 'Élévations latérales haltères', 'musculation', 'epaules', '{}', 'halteres', FALSE, 'charge_reps'),
    ('elevations_laterales_poulie', 'Élévations latérales à la poulie basse', 'musculation', 'epaules', '{}', 'poulie', TRUE, 'charge_reps'),
    ('elevations_laterales_machine', 'Élévations latérales machine', 'musculation', 'epaules', '{}', 'machine', FALSE, 'charge_reps'),
    ('elevations_frontales', 'Élévations frontales haltères', 'musculation', 'epaules', '{}', 'halteres', FALSE, 'charge_reps'),
    ('oiseau_halteres', 'Oiseau buste penché haltères', 'musculation', 'epaules', '{dos}', 'halteres', FALSE, 'charge_reps'),
    ('pec_deck_inverse', 'Pec deck inversé', 'musculation', 'epaules', '{dos}', 'machine', FALSE, 'charge_reps'),
    ('tirage_visage', 'Tirage visage à la corde', 'musculation', 'epaules', '{dos}', 'poulie', FALSE, 'charge_reps'),
    ('rotation_externe_poulie', 'Rotation externe à la poulie', 'musculation', 'epaules', '{}', 'poulie', TRUE, 'charge_reps'),
    ('curl_barre', 'Curl barre droite', 'musculation', 'biceps', '{avant_bras}', 'barre', FALSE, 'charge_reps'),
    ('curl_barre_ez', 'Curl barre EZ', 'musculation', 'biceps', '{avant_bras}', 'barre', FALSE, 'charge_reps'),
    ('curl_pupitre_barre', 'Curl pupitre à la barre', 'musculation', 'biceps', '{}', 'barre', FALSE, 'charge_reps'),
    ('curl_pupitre_machine', 'Curl pupitre machine', 'musculation', 'biceps', '{}', 'machine', FALSE, 'charge_reps'),
    ('curl_pupitre_marteau', 'Curl marteau sur pupitre', 'musculation', 'biceps', '{avant_bras}', 'halteres', TRUE, 'charge_reps'),
    ('curl_halteres', 'Curl haltères classique, paume vers le haut', 'musculation', 'biceps', '{avant_bras}', 'halteres', FALSE, 'charge_reps'),
    ('curl_halteres_rotation', 'Curl haltères avec rotation', 'musculation', 'biceps', '{avant_bras}', 'halteres', FALSE, 'charge_reps'),
    ('curl_incline', 'Curl incliné haltères, paume vers le haut', 'musculation', 'biceps', '{}', 'halteres', FALSE, 'charge_reps'),
    ('curl_marteau', 'Curl marteau haltère, un bras', 'musculation', 'biceps', '{avant_bras}', 'halteres', TRUE, 'charge_reps'),
    ('curl_marteau_incline', 'Curl marteau sur banc incliné', 'musculation', 'biceps', '{avant_bras}', 'halteres', TRUE, 'charge_reps'),
    ('curl_corde_poulie', 'Curl à la corde, poulie basse', 'musculation', 'biceps', '{avant_bras}', 'poulie', FALSE, 'charge_reps'),
    ('curl_corde_dos_poulie', 'Curl à la corde dos à la poulie', 'musculation', 'biceps', '{avant_bras}', 'poulie', FALSE, 'charge_reps'),
    ('curl_poulie_basse_barre', 'Curl poulie basse à la barre droite', 'musculation', 'biceps', '{avant_bras}', 'poulie', FALSE, 'charge_reps'),
    ('curl_machine', 'Curl biceps machine', 'musculation', 'biceps', '{}', 'machine', FALSE, 'charge_reps'),
    ('curl_inverse_barre', 'Curl inversé barre, paume vers le sol', 'musculation', 'avant_bras', '{biceps}', 'barre', FALSE, 'charge_reps'),
    ('curl_inverse_poulie', 'Curl inversé à la poulie, paume vers le sol', 'musculation', 'avant_bras', '{biceps}', 'poulie', FALSE, 'charge_reps'),
    ('marche_du_fermier', 'Marche du fermier', 'musculation', 'avant_bras', '{dos,abdominaux}', 'halteres', FALSE, 'duree'),
    ('suspension_barre', 'Suspension à la barre', 'musculation', 'avant_bras', '{dos}', 'poids_du_corps', FALSE, 'duree'),
    ('extension_triceps_corde', 'Extension triceps poulie haute à la corde', 'musculation', 'triceps', '{}', 'poulie', FALSE, 'charge_reps'),
    ('extension_triceps_barre', 'Extension triceps poulie haute à la barre', 'musculation', 'triceps', '{}', 'poulie', FALSE, 'charge_reps'),
    ('extension_triceps_dessus_tete', 'Extension triceps au-dessus de la tête, corde', 'musculation', 'triceps', '{}', 'poulie', FALSE, 'charge_reps'),
    ('extension_nuque_haltere', 'Extension nuque haltère', 'musculation', 'triceps', '{}', 'halteres', FALSE, 'charge_reps'),
    ('barre_au_front', 'Barre au front', 'musculation', 'triceps', '{}', 'barre', FALSE, 'charge_reps'),
    ('extension_triceps_machine', 'Extension triceps machine', 'musculation', 'triceps', '{}', 'machine', FALSE, 'charge_reps'),
    ('dips', 'Dips aux barres parallèles', 'musculation', 'triceps', '{pectoraux,epaules}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('dips_machine', 'Machine à dips assis', 'musculation', 'triceps', '{pectoraux}', 'machine', FALSE, 'charge_reps'),
    ('developpe_couche_serre', 'Développé couché prise serrée', 'musculation', 'triceps', '{pectoraux,epaules}', 'barre', FALSE, 'charge_reps'),
    ('kickback_triceps', 'Kickback triceps haltère', 'musculation', 'triceps', '{}', 'halteres', TRUE, 'charge_reps'),
    ('squat_barre', 'Squat barre', 'musculation', 'quadriceps', '{fessiers,adducteurs,lombaires}', 'barre', FALSE, 'charge_reps'),
    ('squat_avant', 'Squat avant, prise haltérophilie', 'musculation', 'quadriceps', '{fessiers,abdominaux}', 'barre', FALSE, 'charge_reps'),
    ('squat_avant_bras_croises', 'Squat avant, bras croisés', 'musculation', 'quadriceps', '{fessiers,abdominaux}', 'barre', FALSE, 'charge_reps'),
    ('squat_goblet', 'Squat goblet', 'musculation', 'quadriceps', '{fessiers}', 'halteres', FALSE, 'charge_reps'),
    ('squat_smith', 'Squat au cadre guidé', 'musculation', 'quadriceps', '{fessiers}', 'machine', FALSE, 'charge_reps'),
    ('hack_squat', 'Hack squat', 'musculation', 'quadriceps', '{fessiers}', 'machine', FALSE, 'charge_reps'),
    ('presse_cuisses', 'Presse à cuisses', 'musculation', 'quadriceps', '{fessiers,adducteurs}', 'machine', FALSE, 'charge_reps'),
    ('leg_extension', 'Leg extension', 'musculation', 'quadriceps', '{}', 'machine', FALSE, 'charge_reps'),
    ('fentes_halteres', 'Fentes haltères', 'musculation', 'quadriceps', '{fessiers}', 'halteres', TRUE, 'charge_reps'),
    ('squat_bulgare', 'Squat bulgare', 'musculation', 'quadriceps', '{fessiers}', 'halteres', TRUE, 'charge_reps'),
    ('montee_sur_banc', 'Montée sur banc', 'musculation', 'quadriceps', '{fessiers}', 'halteres', TRUE, 'charge_reps'),
    ('souleve_de_terre', 'Soulevé de terre, double pronation', 'musculation', 'lombaires', '{fessiers,ischios,dos,avant_bras}', 'barre', FALSE, 'charge_reps'),
    ('souleve_de_terre_prise_mixte', 'Soulevé de terre, prise mixte', 'musculation', 'lombaires', '{fessiers,ischios,dos,avant_bras}', 'barre', FALSE, 'charge_reps'),
    ('souleve_barre_hexagonale', 'Soulevé de terre à la barre hexagonale', 'musculation', 'lombaires', '{fessiers,quadriceps,dos,avant_bras}', 'barre', FALSE, 'charge_reps'),
    ('souleve_de_terre_roumain', 'Soulevé de terre roumain barre', 'musculation', 'ischios', '{fessiers,lombaires}', 'barre', FALSE, 'charge_reps'),
    ('souleve_roumain_halteres', 'Soulevé de terre roumain haltères', 'musculation', 'ischios', '{fessiers,lombaires}', 'halteres', FALSE, 'charge_reps'),
    ('leg_curl_assis', 'Leg curl assis', 'musculation', 'ischios', '{}', 'machine', FALSE, 'charge_reps'),
    ('leg_curl_allonge', 'Leg curl allongé', 'musculation', 'ischios', '{}', 'machine', FALSE, 'charge_reps'),
    ('curl_nordique', 'Curl nordique', 'musculation', 'ischios', '{}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('banc_lombaires_45', 'Banc à lombaires à 45°', 'musculation', 'lombaires', '{fessiers,ischios}', 'machine', FALSE, 'charge_reps'),
    ('extension_lombaire_machine', 'Extension lombaire machine', 'musculation', 'lombaires', '{}', 'machine', FALSE, 'charge_reps'),
    ('hip_thrust_barre', 'Hip thrust barre', 'musculation', 'fessiers', '{ischios}', 'barre', FALSE, 'charge_reps'),
    ('hip_thrust_machine', 'Machine à hip thrust', 'musculation', 'fessiers', '{ischios}', 'machine', FALSE, 'charge_reps'),
    ('pont_fessier', 'Pont fessier', 'musculation', 'fessiers', '{ischios}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('kickback_poulie', 'Extension de hanche à la poulie', 'musculation', 'fessiers', '{}', 'poulie', TRUE, 'charge_reps'),
    ('abducteurs_machine', 'Machine à abducteurs', 'musculation', 'fessiers', '{}', 'machine', FALSE, 'charge_reps'),
    ('tirage_entre_jambes', 'Tirage entre les jambes à la poulie', 'musculation', 'fessiers', '{ischios}', 'poulie', FALSE, 'charge_reps'),
    ('adducteurs_machine', 'Machine à adducteurs', 'musculation', 'adducteurs', '{}', 'machine', FALSE, 'charge_reps'),
    ('fente_laterale', 'Fente latérale', 'musculation', 'adducteurs', '{quadriceps,fessiers}', 'halteres', TRUE, 'charge_reps'),
    ('mollets_debout', 'Mollets debout', 'musculation', 'mollets', '{}', 'machine', FALSE, 'charge_reps'),
    ('mollets_presse', 'Mollets à la presse, jambes tendues', 'musculation', 'mollets', '{}', 'machine', FALSE, 'charge_reps'),
    ('mollets_assis', 'Mollets assis', 'musculation', 'mollets', '{}', 'machine', FALSE, 'charge_reps'),
    ('crunch_machine', 'Machine à abdominaux', 'musculation', 'abdominaux', '{}', 'machine', FALSE, 'charge_reps'),
    ('crunch_poulie', 'Crunch à genoux à la poulie', 'musculation', 'abdominaux', '{}', 'poulie', FALSE, 'charge_reps'),
    ('crunch_sol', 'Crunch au sol', 'musculation', 'abdominaux', '{}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('releve_jambes_chaise', 'Relevé de jambes à la chaise romaine', 'musculation', 'abdominaux', '{}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('releve_jambes_suspendu', 'Relevé de jambes suspendu', 'musculation', 'abdominaux', '{avant_bras}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('roulette_abdominaux', 'Roulette abdominale', 'musculation', 'abdominaux', '{}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('planche', 'Planche', 'musculation', 'abdominaux', '{}', 'poids_du_corps', FALSE, 'duree'),
    ('planche_laterale', 'Planche latérale', 'musculation', 'abdominaux', '{}', 'poids_du_corps', TRUE, 'duree'),
    ('insecte_mort', 'Insecte mort', 'musculation', 'abdominaux', '{}', 'poids_du_corps', FALSE, 'charge_reps'),
    ('pallof', 'Rotation bloquée à la poulie (pallof)', 'musculation', 'abdominaux', '{}', 'poulie', TRUE, 'charge_reps'),
    ('course_echauffement', 'Échauffement en footing', 'course', 'cardio', '{}', 'aucun', FALSE, 'duree'),
    ('course_endurance', 'Footing en endurance fondamentale', 'course', 'cardio', '{}', 'aucun', FALSE, 'duree'),
    ('course_endurance_distance', 'Footing en endurance, à la distance', 'course', 'cardio', '{}', 'aucun', FALSE, 'distance'),
    ('course_sortie_longue', 'Sortie longue', 'course', 'cardio', '{}', 'aucun', FALSE, 'distance'),
    ('course_sortie_longue_duree', 'Sortie longue, à la durée', 'course', 'cardio', '{}', 'aucun', FALSE, 'duree'),
    ('course_seuil', 'Bloc au seuil', 'course', 'cardio', '{}', 'aucun', FALSE, 'duree'),
    ('course_fractionne_duree', 'Répétition de fractionné, à la durée', 'course', 'cardio', '{}', 'aucun', FALSE, 'duree'),
    ('course_fractionne_distance', 'Répétition de fractionné, à la distance', 'course', 'cardio', '{}', 'aucun', FALSE, 'distance'),
    ('course_recuperation', 'Récupération trottée ou marchée entre deux répétitions', 'course', 'cardio', '{}', 'aucun', FALSE, 'duree'),
    ('course_allure_specifique', 'Bloc à l''allure de la course objectif', 'course', 'cardio', '{}', 'aucun', FALSE, 'distance'),
    ('course_cotes', 'Répétition en côte', 'course', 'cardio', '{}', 'aucun', FALSE, 'duree'),
    ('course_lignes_droites', 'Lignes droites', 'course', 'cardio', '{}', 'aucun', FALSE, 'distance'),
    ('course_retour_au_calme', 'Retour au calme en footing', 'course', 'cardio', '{}', 'aucun', FALSE, 'duree'),
    ('course_test', 'Test de course chronométré', 'course', 'cardio', '{}', 'aucun', FALSE, 'distance'),
    ('course_competition', 'Course objectif', 'course', 'cardio', '{}', 'aucun', FALSE, 'distance'),
    ('marche', 'Marche', 'course', 'cardio', '{}', 'aucun', FALSE, 'duree'),
    ('cardio_echauffement', 'Échauffement sur machine cardio', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('tapis_marche_inclinee', 'Tapis en marche inclinée', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('rameur', 'Rameur, en continu', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('rameur_intervalles', 'Rameur, une répétition', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('elliptique', 'Elliptique', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('velo_droit', 'Vélo droit ou spinning, en continu', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('velo_intervalles', 'Vélo, une répétition', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('velo_semi_allonge', 'Vélo semi-allongé', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('escalier', 'Escalier ou stepper', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('skierg', 'SkiErg, en continu', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('skierg_intervalles', 'SkiErg, une répétition', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('velo_air', 'Vélo à air, une répétition', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('cardio_recuperation', 'Récupération facile entre deux répétitions', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree'),
    ('cardio_retour_au_calme', 'Retour au calme sur machine cardio', 'cardio', 'cardio', '{}', 'cardio', FALSE, 'duree')
ON CONFLICT (code) DO NOTHING;

-- EXO-2 : ce qu'on fait quand la machine est prise, par ordre de préférence.
INSERT INTO exercice_alternative (id_exercice, id_alternative, rang)
SELECT e.id_exercice, a.id_exercice, v.rang
  FROM (VALUES
    ('developpe_couche_barre', 'developpe_couche_halteres', 1),
    ('developpe_couche_barre', 'presse_pectoraux', 2),
    ('developpe_couche_barre', 'developpe_couche_smith', 3),
    ('developpe_couche_smith', 'presse_pectoraux', 1),
    ('developpe_couche_smith', 'developpe_couche_halteres', 2),
    ('developpe_couche_halteres', 'presse_pectoraux', 1),
    ('developpe_couche_halteres', 'developpe_couche_barre', 2),
    ('developpe_incline_barre', 'developpe_incline_halteres', 1),
    ('developpe_incline_barre', 'presse_inclinee', 2),
    ('developpe_incline_halteres', 'presse_inclinee', 1),
    ('developpe_incline_halteres', 'developpe_incline_barre', 2),
    ('presse_pectoraux', 'developpe_couche_halteres', 1),
    ('presse_pectoraux', 'developpe_couche_smith', 2),
    ('presse_pectoraux', 'pompes', 3),
    ('presse_inclinee', 'developpe_incline_halteres', 1),
    ('presse_inclinee', 'developpe_incline_barre', 2),
    ('pec_deck', 'ecartes_poulies', 1),
    ('pec_deck', 'ecartes_halteres', 2),
    ('ecartes_halteres', 'pec_deck', 1),
    ('ecartes_halteres', 'ecartes_poulies', 2),
    ('ecartes_poulies', 'pec_deck', 1),
    ('ecartes_poulies', 'ecartes_halteres', 2),
    ('pompes', 'presse_pectoraux', 1),
    ('pompes', 'developpe_couche_halteres', 2),
    ('tractions_pronation', 'tractions_neutre', 1),
    ('tractions_pronation', 'tirage_vertical_large', 2),
    ('tractions_pronation', 'tractions_assistees', 3),
    ('tractions_supination', 'tractions_neutre', 1),
    ('tractions_supination', 'tirage_vertical_neutre', 2),
    ('tractions_neutre', 'tirage_vertical_neutre', 1),
    ('tractions_neutre', 'tractions_pronation', 2),
    ('tractions_neutre', 'tractions_assistees', 3),
    ('tractions_assistees', 'tirage_vertical_neutre', 1),
    ('tractions_assistees', 'tirage_vertical_large', 2),
    ('tirage_vertical_large', 'tirage_vertical_neutre', 1),
    ('tirage_vertical_large', 'tractions_assistees', 2),
    ('tirage_vertical_large', 'tractions_pronation', 3),
    ('tirage_vertical_neutre', 'tirage_vertical_large', 1),
    ('tirage_vertical_neutre', 'tractions_neutre', 2),
    ('tirage_vertical_neutre', 'tractions_assistees', 3),
    ('tirage_vertical_supination', 'tirage_vertical_neutre', 1),
    ('tirage_vertical_supination', 'tirage_vertical_large', 2),
    ('tirage_bras_tendus', 'tirage_unilateral_poulie', 1),
    ('tirage_bras_tendus', 'tirage_vertical_large', 2),
    ('tirage_unilateral_poulie', 'tirage_vertical_neutre', 1),
    ('tirage_unilateral_poulie', 'rowing_haltere_un_bras', 2),
    ('rowing_barre', 'rowing_t_appui', 1),
    ('rowing_barre', 'rowing_assis_machine', 2),
    ('rowing_barre', 'rowing_haltere_un_bras', 3),
    ('rowing_barre_supination', 'rowing_barre', 1),
    ('rowing_barre_supination', 'rowing_assis_machine', 2),
    ('rowing_haltere_un_bras', 'rowing_assis_machine', 1),
    ('rowing_haltere_un_bras', 'rowing_poulie_basse', 2),
    ('rowing_haltere_un_bras', 'rowing_t_appui', 3),
    ('rowing_haltere_rotation', 'rowing_haltere_un_bras', 1),
    ('rowing_haltere_rotation', 'rowing_assis_machine', 2),
    ('rowing_assis_machine', 'rowing_poulie_basse', 1),
    ('rowing_assis_machine', 'rowing_t_appui', 2),
    ('rowing_assis_machine', 'rowing_haltere_un_bras', 3),
    ('rowing_poulie_basse', 'rowing_assis_machine', 1),
    ('rowing_poulie_basse', 'rowing_haltere_un_bras', 2),
    ('rowing_poulie_basse', 'rowing_t_appui', 3),
    ('rowing_t_appui', 'rowing_assis_machine', 1),
    ('rowing_t_appui', 'rowing_poulie_basse', 2),
    ('rowing_inverse', 'rowing_assis_machine', 1),
    ('rowing_inverse', 'rowing_poulie_basse', 2),
    ('haussements_halteres', 'marche_du_fermier', 1),
    ('developpe_militaire_barre', 'developpe_epaules_halteres', 1),
    ('developpe_militaire_barre', 'presse_epaules', 2),
    ('developpe_epaules_halteres', 'presse_epaules', 1),
    ('developpe_epaules_halteres', 'developpe_militaire_barre', 2),
    ('developpe_arnold', 'developpe_epaules_halteres', 1),
    ('developpe_arnold', 'presse_epaules', 2),
    ('presse_epaules', 'developpe_epaules_halteres', 1),
    ('presse_epaules', 'developpe_militaire_barre', 2),
    ('elevations_laterales_halteres', 'elevations_laterales_poulie', 1),
    ('elevations_laterales_halteres', 'elevations_laterales_machine', 2),
    ('elevations_laterales_poulie', 'elevations_laterales_halteres', 1),
    ('elevations_laterales_poulie', 'elevations_laterales_machine', 2),
    ('elevations_laterales_machine', 'elevations_laterales_halteres', 1),
    ('elevations_laterales_machine', 'elevations_laterales_poulie', 2),
    ('elevations_frontales', 'presse_epaules', 1),
    ('oiseau_halteres', 'pec_deck_inverse', 1),
    ('oiseau_halteres', 'tirage_visage', 2),
    ('pec_deck_inverse', 'tirage_visage', 1),
    ('pec_deck_inverse', 'oiseau_halteres', 2),
    ('tirage_visage', 'pec_deck_inverse', 1),
    ('tirage_visage', 'oiseau_halteres', 2),
    ('curl_barre', 'curl_corde_poulie', 1),
    ('curl_barre', 'curl_marteau', 2),
    ('curl_barre', 'curl_barre_ez', 3),
    ('curl_barre_ez', 'curl_corde_poulie', 1),
    ('curl_barre_ez', 'curl_marteau', 2),
    ('curl_pupitre_barre', 'curl_pupitre_marteau', 1),
    ('curl_pupitre_barre', 'curl_corde_poulie', 2),
    ('curl_pupitre_machine', 'curl_pupitre_marteau', 1),
    ('curl_pupitre_machine', 'curl_corde_poulie', 2),
    ('curl_pupitre_marteau', 'curl_marteau', 1),
    ('curl_pupitre_marteau', 'curl_corde_poulie', 2),
    ('curl_halteres', 'curl_marteau', 1),
    ('curl_halteres', 'curl_corde_poulie', 2),
    ('curl_halteres_rotation', 'curl_marteau', 1),
    ('curl_halteres_rotation', 'curl_corde_poulie', 2),
    ('curl_incline', 'curl_marteau_incline', 1),
    ('curl_incline', 'curl_marteau', 2),
    ('curl_marteau', 'curl_corde_poulie', 1),
    ('curl_marteau', 'curl_inverse_poulie', 2),
    ('curl_marteau_incline', 'curl_marteau', 1),
    ('curl_marteau_incline', 'curl_corde_poulie', 2),
    ('curl_corde_poulie', 'curl_marteau', 1),
    ('curl_corde_poulie', 'curl_inverse_poulie', 2),
    ('curl_corde_dos_poulie', 'curl_corde_poulie', 1),
    ('curl_corde_dos_poulie', 'curl_marteau', 2),
    ('curl_poulie_basse_barre', 'curl_corde_poulie', 1),
    ('curl_poulie_basse_barre', 'curl_marteau', 2),
    ('curl_machine', 'curl_corde_poulie', 1),
    ('curl_machine', 'curl_marteau', 2),
    ('curl_inverse_barre', 'curl_inverse_poulie', 1),
    ('curl_inverse_barre', 'curl_marteau', 2),
    ('curl_inverse_poulie', 'curl_inverse_barre', 1),
    ('curl_inverse_poulie', 'curl_marteau', 2),
    ('marche_du_fermier', 'suspension_barre', 1),
    ('suspension_barre', 'marche_du_fermier', 1),
    ('extension_triceps_corde', 'extension_triceps_barre', 1),
    ('extension_triceps_corde', 'extension_triceps_machine', 2),
    ('extension_triceps_barre', 'extension_triceps_corde', 1),
    ('extension_triceps_barre', 'extension_triceps_machine', 2),
    ('extension_triceps_dessus_tete', 'extension_nuque_haltere', 1),
    ('extension_triceps_dessus_tete', 'extension_triceps_corde', 2),
    ('extension_nuque_haltere', 'extension_triceps_dessus_tete', 1),
    ('extension_nuque_haltere', 'extension_triceps_corde', 2),
    ('barre_au_front', 'extension_triceps_corde', 1),
    ('barre_au_front', 'extension_triceps_dessus_tete', 2),
    ('extension_triceps_machine', 'extension_triceps_corde', 1),
    ('extension_triceps_machine', 'extension_triceps_barre', 2),
    ('dips', 'dips_machine', 1),
    ('dips', 'extension_triceps_corde', 2),
    ('dips_machine', 'dips', 1),
    ('dips_machine', 'extension_triceps_corde', 2),
    ('developpe_couche_serre', 'dips_machine', 1),
    ('developpe_couche_serre', 'extension_triceps_corde', 2),
    ('kickback_triceps', 'extension_triceps_corde', 1),
    ('squat_barre', 'hack_squat', 1),
    ('squat_barre', 'presse_cuisses', 2),
    ('squat_barre', 'squat_smith', 3),
    ('squat_avant', 'squat_avant_bras_croises', 1),
    ('squat_avant', 'squat_goblet', 2),
    ('squat_avant', 'hack_squat', 3),
    ('squat_avant_bras_croises', 'squat_goblet', 1),
    ('squat_avant_bras_croises', 'hack_squat', 2),
    ('squat_goblet', 'hack_squat', 1),
    ('squat_goblet', 'presse_cuisses', 2),
    ('squat_smith', 'hack_squat', 1),
    ('squat_smith', 'presse_cuisses', 2),
    ('hack_squat', 'presse_cuisses', 1),
    ('hack_squat', 'squat_smith', 2),
    ('hack_squat', 'squat_goblet', 3),
    ('presse_cuisses', 'hack_squat', 1),
    ('presse_cuisses', 'squat_smith', 2),
    ('presse_cuisses', 'squat_goblet', 3),
    ('leg_extension', 'squat_goblet', 1),
    ('fentes_halteres', 'squat_bulgare', 1),
    ('fentes_halteres', 'presse_cuisses', 2),
    ('squat_bulgare', 'fentes_halteres', 1),
    ('squat_bulgare', 'presse_cuisses', 2),
    ('montee_sur_banc', 'fentes_halteres', 1),
    ('souleve_de_terre', 'souleve_barre_hexagonale', 1),
    ('souleve_de_terre', 'souleve_de_terre_roumain', 2),
    ('souleve_de_terre_prise_mixte', 'souleve_de_terre', 1),
    ('souleve_de_terre_prise_mixte', 'souleve_barre_hexagonale', 2),
    ('souleve_barre_hexagonale', 'souleve_de_terre', 1),
    ('souleve_de_terre_roumain', 'souleve_roumain_halteres', 1),
    ('souleve_de_terre_roumain', 'leg_curl_assis', 2),
    ('souleve_de_terre_roumain', 'banc_lombaires_45', 3),
    ('souleve_roumain_halteres', 'souleve_de_terre_roumain', 1),
    ('souleve_roumain_halteres', 'leg_curl_assis', 2),
    ('leg_curl_assis', 'leg_curl_allonge', 1),
    ('leg_curl_assis', 'souleve_roumain_halteres', 2),
    ('leg_curl_allonge', 'leg_curl_assis', 1),
    ('leg_curl_allonge', 'souleve_roumain_halteres', 2),
    ('curl_nordique', 'leg_curl_assis', 1),
    ('curl_nordique', 'leg_curl_allonge', 2),
    ('banc_lombaires_45', 'extension_lombaire_machine', 1),
    ('banc_lombaires_45', 'souleve_roumain_halteres', 2),
    ('extension_lombaire_machine', 'banc_lombaires_45', 1),
    ('hip_thrust_barre', 'hip_thrust_machine', 1),
    ('hip_thrust_barre', 'pont_fessier', 2),
    ('hip_thrust_machine', 'hip_thrust_barre', 1),
    ('hip_thrust_machine', 'pont_fessier', 2),
    ('pont_fessier', 'hip_thrust_machine', 1),
    ('kickback_poulie', 'hip_thrust_machine', 1),
    ('abducteurs_machine', 'kickback_poulie', 1),
    ('tirage_entre_jambes', 'hip_thrust_machine', 1),
    ('tirage_entre_jambes', 'souleve_roumain_halteres', 2),
    ('adducteurs_machine', 'fente_laterale', 1),
    ('fente_laterale', 'adducteurs_machine', 1),
    ('mollets_debout', 'mollets_presse', 1),
    ('mollets_debout', 'mollets_assis', 2),
    ('mollets_presse', 'mollets_debout', 1),
    ('mollets_presse', 'mollets_assis', 2),
    ('mollets_assis', 'mollets_debout', 1),
    ('mollets_assis', 'mollets_presse', 2),
    ('crunch_machine', 'crunch_poulie', 1),
    ('crunch_machine', 'crunch_sol', 2),
    ('crunch_poulie', 'crunch_machine', 1),
    ('crunch_poulie', 'crunch_sol', 2),
    ('crunch_sol', 'crunch_machine', 1),
    ('crunch_sol', 'crunch_poulie', 2),
    ('releve_jambes_chaise', 'releve_jambes_suspendu', 1),
    ('releve_jambes_chaise', 'crunch_machine', 2),
    ('releve_jambes_suspendu', 'releve_jambes_chaise', 1),
    ('releve_jambes_suspendu', 'crunch_machine', 2),
    ('roulette_abdominaux', 'planche', 1),
    ('roulette_abdominaux', 'crunch_poulie', 2),
    ('planche', 'insecte_mort', 1),
    ('planche_laterale', 'pallof', 1),
    ('insecte_mort', 'planche', 1),
    ('pallof', 'planche_laterale', 1),
    ('tapis_marche_inclinee', 'escalier', 1),
    ('tapis_marche_inclinee', 'elliptique', 2),
    ('tapis_marche_inclinee', 'velo_droit', 3),
    ('rameur', 'skierg', 1),
    ('rameur', 'elliptique', 2),
    ('rameur', 'velo_droit', 3),
    ('rameur_intervalles', 'skierg_intervalles', 1),
    ('rameur_intervalles', 'velo_intervalles', 2),
    ('elliptique', 'velo_droit', 1),
    ('elliptique', 'tapis_marche_inclinee', 2),
    ('elliptique', 'rameur', 3),
    ('velo_droit', 'velo_semi_allonge', 1),
    ('velo_droit', 'elliptique', 2),
    ('velo_droit', 'rameur', 3),
    ('velo_intervalles', 'rameur_intervalles', 1),
    ('velo_intervalles', 'velo_air', 2),
    ('velo_semi_allonge', 'velo_droit', 1),
    ('velo_semi_allonge', 'elliptique', 2),
    ('escalier', 'tapis_marche_inclinee', 1),
    ('escalier', 'elliptique', 2),
    ('skierg', 'rameur', 1),
    ('skierg', 'velo_droit', 2),
    ('skierg_intervalles', 'rameur_intervalles', 1),
    ('skierg_intervalles', 'velo_intervalles', 2),
    ('velo_air', 'velo_intervalles', 1),
    ('velo_air', 'rameur_intervalles', 2)
  ) AS v(code, alternative, rang)
  JOIN exercice e ON e.code = v.code
  JOIN exercice a ON a.code = v.alternative
ON CONFLICT (id_exercice, id_alternative) DO NOTHING;
